
sudo: required

language: go

services:
  - docker

before_install:
  - docker build -t spad .

script:
  - docker run -it -v `pwd`:/work spad

deploy:
    skip_cleanup: true
    provider: script
    script: chmod +x deploy.sh && deploy.sh
    on:
        branch: master
